In [1]:
import tensorflow as tf

In [2]:
# random tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3, 2, 3))
random_1

Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ]],

       [[ 0.09988727, -0.50998646, -0.7535805 ],
        [-0.57166284,  0.1480774 , -0.23362993]],

       [[-0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 ]]], dtype=float32)>

In [3]:
# tensor shuffling
shuffle_random_1 = tf.random.shuffle(random_1)
shuffle_random_1

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[-0.3522796 ,  0.40621263, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.4462975 ]],

       [[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ]],

       [[ 0.09988727, -0.50998646, -0.7535805 ],
        [-0.57166284,  0.1480774 , -0.23362993]]], dtype=float32)>

In [4]:
# tensor of ones
tf.ones((4,6))

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [5]:
# tensor of zeros
tf.zeros((5,2))

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [6]:
# convert numpy array to tensor
import numpy as np
array_1 = np.arange(1, 25, dtype=np.int32)
A = tf.constant(array_1, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [7]:
# rank 4 tensor
rank_4 = tf.zeros((2, 3, 4, 5))
rank_4

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [8]:
# tensor attributes
rank_4.shape, rank_4.ndim, tf.size(rank_4)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [9]:
# indexing
rank_4[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [10]:
rank_4[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [11]:
rank_4[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [12]:
rank_2 = tf.constant(((10, 7), (3, 4)))
rank_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [13]:
rank_2[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [14]:
# adding dim
rank_3 = rank_2[..., tf.newaxis]
rank_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [15]:
# also adding dim
tf.expand_dims(rank_2, axis=-1) # expanding on last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [16]:
# operations
tensor = tf.constant(((10, 7), (3, 4)))
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [17]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [18]:
tensor * 20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 140],
       [ 60,  80]], dtype=int32)>

In [19]:
tensor - 50

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-40, -43],
       [-47, -46]], dtype=int32)>

In [20]:
tf.multiply(tensor, 20) # tf functions faster than base op

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 140],
       [ 60,  80]], dtype=int32)>

In [21]:
# matrix multiplication
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [22]:
t1 = tf.constant(((1, 2, 5),
                  (7, 2, 1),
                  (3, 3, 3)))
t2 = tf.constant(((3, 5),
                  (6, 7),
                  (1, 8)))
t1, t2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [23]:
tf.matmul(t1, t2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [24]:
tf.tensordot(t1, t2, axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [25]:
# change dtype of tensor
A = tf.constant(((1.9, 8.3),
                (4.5, 6.9)))
tf.cast(A, dtype=tf.float16)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1.9, 8.3],
       [4.5, 6.9]], dtype=float16)>

In [26]:
# tensor aggregation
B = tf.constant(np.random.randint(0, 100, size=50))
B

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([28, 32, 53, 62,  4, 70, 58, 80, 97, 58,  3, 22, 57, 22, 84, 65,  1,
       96, 10, 20, 22, 47, 55, 73, 75,  7, 69, 28, 72, 36, 48, 74, 25, 51,
       70, 89, 76, 14, 53, 66, 25, 22,  4, 58, 82, 65, 37, 47, 71, 71])>

In [27]:
tf.reduce_min(B)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [28]:
tf.reduce_max(B)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [29]:
tf.reduce_mean(B)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [30]:
tf.reduce_sum(B)

<tf.Tensor: shape=(), dtype=int64, numpy=2454>

In [31]:
tf.math.reduce_variance(tf.cast(B, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=710.07355>

In [32]:
tf.math.reduce_std(tf.cast(B, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.647207>

In [33]:
tf.argmax(B)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [34]:
tf.argmin(B)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [35]:
# squeezing
tf.random.set_seed(42)
C = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
C

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [36]:
tf.squeeze(C)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [37]:
# one-hot encoding
some_list = [0, 1, 2, 3]

tf.one_hot(some_list, depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [38]:
# squaring
D = tf.reshape(tf.range(1, 11), shape=(2, 5))
tf.square(D)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]], dtype=int32)>

In [39]:
# square rooting
tf.sqrt(tf.cast(D, dtype=tf.float32))

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1.       , 1.4142135, 1.7320508, 2.       , 2.236068 ],
       [2.4494898, 2.6457512, 2.828427 , 3.       , 3.1622777]],
      dtype=float32)>

In [40]:
# log
tf.math.log(tf.cast(D, dtype=tf.float32))

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[0.       , 0.6931472, 1.0986122, 1.3862944, 1.6094378],
       [1.7917594, 1.94591  , 2.0794415, 2.1972246, 2.3025851]],
      dtype=float32)>

In [41]:
# checking GPU
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]